server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

#微信号
weixin:
  config:
    originalid: gh_3b4d558cc61b
    token: b8b6
    app-id: wx9c6d6ef462e027cd
    app-secret: 64682d9d7afc69748f8b9ea85db15d5e
    template_id: RbEZ2jo47dQmF4A7_Ku7RsDy1x_5by6bk1Ox6rPCl4Y